server:
  port: 8086

spring:
  application:
    name: evaluate-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lisoft
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    template-loader-path: classpath:/templates

  thymeleaf:
    cache: false

  mvc:
    view:
      prefix: /static/
      suffix: .html



book:
  author: Mr.wu
logging:
  file: D:/u disk/log.log
  level:
    org:
      springframework:
        web: DEBUG
      security: INFO